apps/storybook/stories/input/input.stories.tsx, apps/storybook/stories/text/text.stories.tsx, packages/ui/src/index.ts, packages/ui/src/input/index.ts, packages/ui/src/input/input.tsx, packages/ui/src/input/style.css.ts, packages/ui/src/input/types.ts
재사용성을 높이기 위해 디자인 시스템에 input 컴포넌트를 추가하였습니다.
input 컴포넌트 제작
input 컴포넌트 스토리 작성
- close #13
=> feat :: input 컴포넌트 생성

apps/storybook/stories/toast/toast.stories.tsx, packages/ui/src/index.ts, packages/ui/src/toast/index.ts, packages/ui/src/toast/styles.css.ts, packages/ui/src/toast/toast.tsx, packages/ui/src/toast/toastContainer.tsx, packages/ui/src/toast/toastContext.ts, packages/ui/src/toast/toastProvider.tsx, packages/ui/src/toast/types.ts
디자인 시스템 토스트 추가
- 토스트 컴포넌트 추가
- 토스트 스토리 작성
- close #17
=> merge :: Toast

apps/company/src/app/registration/page.tsx
=> develop -> main

packages/ui/src/button/button.tsx, packages/ui/src/button/types.ts
버튼 컴포넌트 버그 해결
- 버튼 isLoading true일 때 disabled가 되고 spinner가 나와야하지만 나오지 않는 버그 발생
- close #42
=> fix :: 버튼 로딩 스피너 버그 해결

apps/company/src/apis/company/types.ts, apps/company/src/apis/recruitments/types.ts, apps/company/src/app/page.tsx, apps/company/src/app/recruitments/[id]/page.tsx, apps/company/src/app/recruitments/page.tsx, apps/company/src/app/registration/page.tsx, apps/company/src/components/modal/recruitmentModal/recruitmentModal.tsx, apps/company/src/store/addCodeState.ts
모집의뢰서와 관련된 버그를 수정합니다.
- 모집 분야 수정
- 기술 및 직무 추가시 상세조회에서 조회되도록 하기
- 모집날짜 시작일 기본값 없음 -> 모집날짜 시작일 기본값 설정
- 채용 절차 close 버튼을 눌렀을 때 모달 종료 안됨 -> close 버튼 없앰
- 성적 숫자가 아닌 문자열 입력 가능함 -> 숫자만 입력되도록
- close #47
=> merge :: 모집의뢰서 버그 수정

renovate.json
renovate 봇을 삭제합니다
삭제하는 이유는 다음과 같습니다
- 브랜치 관리 어려움
- 팀원들이 renovate 사용으로 인해 이득이 되는 부분이 없다고 느낌
- pr 관리 복잡
- 커밋 히스토리 복잡
- 굳이 라이브러리 업데이트 사항이 반영되지 않아도 서비스에 큰 문제가 없음
- close #74
=> merge :: delete renovate.json

.pnp.cjs, apps/admin/package.json, apps/admin/src/components/common/dateRangePicker.tsx, apps/admin/src/components/company/row.tsx, apps/policy/src/router.tsx, yarn.lock
admin에서 빌드가 터지는 현상을 수정하였습니다
- admin의 typescript 버전을 company와 통일시키며 5.0.3으로 낮췄습니다.
- eslint에 의해 사용되지 않는 코드들이 걸리는 현상을 미사용 코드를 제거하여 해결하였습니다.
- close #91
=> admin 빌드 오류 수정

apps/company/src/app/registration/page.tsx
기업등록 api 요청시 fax에 하이픈 제거되지 않은 상태로 request를 날려 fax 최대 글자 조건을 충족하지 못해 등록에 실패하는 현상을 해결하였습니다.
또한 fax는 필수값이 아니기 때문에 값이 없는경우는 필드 값을 보내지 않도록 수정하였습니다.
- request 요청시 fax hypen 제거
- fax가 공백인 경우 해당 필드 제외하여 전송
- close #95
=> 기업 등록 api 요청시 fax 하이픈 제거

apps/company/sentry.client.config.ts, apps/company/src/apis/axios.ts
- sentry Replay시 마스킹을 제거합니다.
- sentry 에러 캡처링
https://teawon.github.io/react/Sentry/#1-%EA%B0%9C%EC%9A%94
이후 이 블로그 참고해서 Sentry 모니터링 Group화나 태그를 나눌 수 있는데 이 작업도 나중에 하면 좋을듯합니다.
- close #100
=> feat :: sentry 에러 캡처링 및 Replay 마스킹 제거

apps/company/src/app/registration/page.tsx
기업 등록 시 이메일 형식이 알맞지 않은 경우 에러 메세지를 띄워줍니다.
#108 
- close #
=> 이메일 형식 오류 핸들링 (#108)

apps/company/src/apis/company/types.ts, apps/company/src/app/registration/page.tsx
기업을 수정할 때 사업 분야와 사업 등록증은 수정이 불가합니다.
#102 
- close #
=> 기업 수정 시 사업 분야, 사업 등록증 비활성화 처리

apps/company/src/app/registration/page.tsx
이미지를 업로드 할 때 이름에 특수문자가 있으면 toast를 띄웠습니다.
- close #112
=> feat :: 특수문자 막기

apps/company/src/app/registration/page.tsx
근로자 수가 32767명을 넘으면 32767명으로 입력되게 수정하였습니다.
- close #103
=> feat :: 근로자 수 막기

apps/company/src/app/registration/page.tsx
=> 컴퍼니 코드 오류 수정

apps/company/src/apis/company/types.ts, apps/company/src/app/registration/page.tsx, apps/company/src/components/inputTemplate/index.tsx
기업 등록 시 기존에 있던 담당자 2와 팩스번호를 제외합니다
#115 
- close #
=> 담당자 2, 팩스 번호 삭제

apps/company/src/apis/company/types.ts, apps/company/src/app/registration/page.tsx
기업 등록 시 사업자 등록증을 nullable 처리해서 스킵이 가능하도록 합니다
#120 
- close #
=> 사업자 등록증 nullable 처리

apps/company/src/app/registration/page.tsx
=> 회사 소개 글자수 제한

apps/company/src/app/recruitments/[id]/page.tsx
산학부 피드백에 따라 바뀐 ui 수정
- close #
=> chore :: 모집의뢰서 수정

apps/company/src/app/registration/page.tsx
=> 사업자 등록증 수정

apps/company/src/app/page.tsx, apps/company/src/app/recruitments/[id]/page.tsx
=> 기업 로그인 방식 변경

apps/company/src/apis/company/types.ts, apps/company/src/app/company/page.tsx
=> 내 기업정보 요소 수정

apps/company/src/app/my/page.tsx
=> feat :: 모집의뢰서만 보이게

apps/company/src/apis/recruitments/types.ts, apps/company/src/app/recruitments/[id]/page.tsx, apps/company/src/app/recruitments/page.tsx
=> feat :: 모집의뢰서 디자인 수정

apps/company/src/app/recruitments/[id]/page.tsx
=> fix :: 빌드 에러 수정

apps/company/src/apis/company/types.ts, apps/company/src/app/company/page.tsx, apps/company/src/app/company/style.ts, apps/company/src/app/registration/page.tsx, apps/company/src/components/companyContentTemplate/index.tsx, apps/company/src/components/modal/editModal/editModal.tsx, apps/company/src/components/modal/editModal/style.ts
=> 내 기업정보 페이지 값 변경

apps/company/src/components/modal/editModal/editModal.tsx, apps/company/src/components/modal/editModal/style.ts, apps/company/src/components/modal/logout/logoutModal.tsx, apps/company/src/components/modal/logout/style.ts, apps/company/src/store/modalStore.ts
=> 로그아웃 모달 추가

apps/company/src/apis/recruitments/index.ts, apps/company/src/apis/recruitments/types.ts, apps/company/src/app/recruitments/chose/page.tsx, apps/company/src/app/recruitments/chose/style.ts, apps/company/src/hooks/apis/useRecruitmentsApi.ts
=> 모집의뢰서 존재할 경우 등록 막기

apps/company/src/app/registration/page.tsx
=> 전화번호 하이픈 제거

apps/company/src/app/my/page.tsx
=> 모집의뢰서 링크 연결

apps/company/src/app/recruitments/chose/page.tsx
=> 모집의뢰서 추가작성 막기 수정

apps/company/src/apis/auth/index.ts, apps/company/src/apis/axios.ts, apps/company/src/app/recruitments/[id]/page.tsx, apps/company/src/app/recruitments/page.tsx, apps/company/src/app/registration/page.tsx, apps/company/src/components/modal/index.tsx, apps/company/src/components/modal/recruitmentModal/recruitmentModal.tsx, apps/company/src/components/modal/techModal/techModal.tsx, apps/company/src/hooks/apis/useCompanyApi.ts
`#170` 이슈 'COMPANY 오류 수정' 을 해결합니다.
1. 기업이 등록되지 않는 오류 → 서버 오류
2. 등록된 모집의뢰서에 들어갈 때 잘못된 토큰을 사용하는 오류 → 서버 오류
3. 토큰이 없어도 로그인 페이지로 redirect하는 등의 조치를 취하지 않고, api를 요청하는 오류 → 해결
4. 캘린더 아이콘의 cursor가 변경되나 클릭 동작이 없어 시각적 혼란을 주는 오류 → 해결
5. 사용 기술을 선택할 때, 기술이 2개(선택한 것이 중복되어)씩 선택 및 삭제되는 오류 → 해결
6. 모집의뢰서 입력 시, required input을 입력하지 않아도 api를 요청하는 오류 → 해결
7. 모집분야 추가에서 드래그를 통한 채용인원 입력 변경과 모달 스크롤이 동시에 진행되는 오류 → 해결
8. 기업 등록할 떄 총 근로자 수에서 NaN이 들어가는 오류 → 해결
서버 오류로 전환된 이슈는 경우 현재 고치고 있습니다.
- close #170
=> COMPANY 오류 수정
